[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mitomorph"
version = "0.1.0"
description = "Mitochondrial Morphology Analysis Pipeline for Spinal Cord Injury Research"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
mitomorph = "mitomorph.cli:cli"

[tool.black]
line-length = 110

[tool.pytest.ini_options]
testpaths = ["tests"]
